### ISSUE TITLE
pydantic error when configuring a VPN client

### ISSUE THREAD

**Issue by Lab-8916100448256** [tituspijean/wireguard_client_ynh#14]
### Describe the bug

An error happen when configuring a new wireguard client VPN

### Context

- Hardware:ODroid HC4
- YunoHost version: 12.0.7 
- I have access to my server: Through SSH & through the webadmin & direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - System installed from latst CLIC image
- Using, or trying to install package version/branch: latest version from yunohost apps catalog

### Steps to reproduce

   1. Go to '/yunohost/admin/#/apps/wireguard_client/main'
   2. Add a new configuration in teh 'List of VPN clients to handle'
   3. clic on the 'Browse' button and add a wireguard .conf file
   4. clic on the save button
   5. An error is displayed

### Expected behavior

no error, vpn client cofnigured and working

### Logs

```
12.fr yunohost-api[1650]: Traceback (most recent call last):
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:   File "/usr/lib/python3/dist-packages/moulinette/interfaces/api.py", line 473, in process
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:     ret = self.actionsmap.process(arguments, timeout=30, route=_route)
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:   File "/usr/lib/python3/dist-packages/moulinette/actionsmap.py", line 561, in process
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:     return func(**arguments)
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:            ^^^^^^^^^^^^^^^^^
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:   File "/usr/lib/python3/dist-packages/yunohost/app.py", line 1853, in app_config_get
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:     return config_.get(key, mode)
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:            ^^^^^^^^^^^^^^^^^^^^^^
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:   File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 476, in get
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:     self.config, self.form = self._get_config_panel(prevalidate=False)
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:   File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 803, in _get_config_panel
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:     config = ConfigPanelModel(**raw_config)
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:   File "/usr/lib/python3/dist-packages/yunohost/utils/configpanel.py", line 300, in __init__
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:     super().__init__(version=version, i18n=i18n, panels=panels)
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:   File "/usr/lib/python3/dist-packages/pydantic/main.py", line 342, in __init__
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:     raise validation_error
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]: pydantic.error_wrappers.ValidationError: 1 validation error for ConfigPanelModel
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]: panels -> 0 -> sections -> 2 -> options -> 1 -> FileOption -> accept
Nov 25 08:13:36 clic-hc4.lab12.fr yunohost-api[1650]:   value is not a valid list (type=type_error.list)
```

**Comment by Lab-8916100448256** [comment]
Fixed by PR #15
